USE pro_business_db;

-- pro_business_db.SUPPLIER definition
CREATE TABLE IF NOT EXISTS SUPPLIER (
	ID BIGINT NOT NULL auto_increment,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(30),
	PHONE_NUMBER VARCHAR (20),
	MOBILE_NUMBER VARCHAR(20),
	FAX_NUMBER VARCHAR(20),
	ADDRESS VARCHAR(250),
	CITY VARCHAR(30),
	WEBSITE VARCHAR(50),
    CONTACT VARCHAR(250),
    CAPPED_BALANCE DECIMAL(11, 3),
    INITIAL_BALANCE DECIMAL(11, 3),
    PATENT VARCHAR(30),
    ICE VARCHAR(30),
	CREATION_DATE DATE NOT NULL,
	UUID VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
)ENGINE=InnoDB CHARACTER SET=UTF8MB4;

COMMIT;
