USE pro_business_db;

-- pro_business_db.PRODUCT_FAMILY definition
CREATE TABLE IF NOT EXISTS PRODUCT_FAMILY (
    ID_PRODUCT_FAMILY BIGINT NOT NULL auto_increment,
    UUID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID_PRODUCT_FAMILY)
    )ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- pro_business_db.PRODUCT definition
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID_PRODUCT BIGINT NOT NULL auto_increment,
    UUID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    MEASURE_UNITE VARCHAR(30),
    VAT_RATE DECIMAL(11, 2),
    BUYING_PRICE DECIMAL(11, 3),
    RESELLER_PRICE DECIMAL(11, 3),
    PUBLIC_SALE_PRICE DECIMAL(11, 3),
    CURRENT_STOCK INT,
    INITIAL_STOCK INT,
    INITIAL_STOCK_DATE DATE,
    MINIMAL_STOCK INT,
    MAXIMAL_STOCK INT,
    CREATION_DATE DATE,
    ID_PRODUCT_FAMILY BIGINT,
    PRIMARY KEY(ID_PRODUCT),
    CONSTRAINT `FK_PRODUCT_FAMILY` FOREIGN KEY (ID_PRODUCT_FAMILY) REFERENCES `PRODUCT_FAMILY` (ID_PRODUCT_FAMILY)
    ON DELETE RESTRICT
    )ENGINE=InnoDB CHARACTER SET=UTF8;

DELIMITER $$

DROP TRIGGER IF EXISTS BEFORE_PRODUCT_FAMILY_DELETE $$

CREATE TRIGGER BEFORE_PRODUCT_FAMILY_DELETE
    BEFORE DELETE
    ON PRODUCT_FAMILY FOR EACH ROW
BEGIN
    UPDATE PRODUCT SET ID_PRODUCT_FAMILY = NULL WHERE ID_PRODUCT_FAMILY = OLD.ID_PRODUCT_FAMILY;
END$$

DELIMITER ;

COMMIT;

