USE pro_business_db;

-- pro_business_db.ORGANIZATION definition
CREATE TABLE IF NOT EXISTS ORGANIZATION (
    ORG_ID INT(11) NOT NULL auto_increment,
    ORG_ID_PARENT INT(11) NOT NULL,
    ORG_ID_GROUP_HEAD INT(11) NOT NULL,
    ORG_LABEL VARCHAR(100) NOT NULL,
    ORG_CODE_EXTERN VARCHAR(100) NOT NULL UNIQUE,
    ORG_TYPE VARCHAR(1),
    ORG_EMAIL VARCHAR(100) UNIQUE,
    ORG_ADDRESS TEXT,
    ORG_CITY VARCHAR(100),
    ORG_POSTAL_CODE VARCHAR(15),
    ORG_PHONE_NUMBER VARCHAR(30),
    ORG_CREATION_DATE DATE NOT NULL,
    ORG_LAST_EDITION_DATE DATE,
    ORG_ACTIVATION_DATE DATE,
    ORG_INACTIVATION_DATE DATE,
    ORG_IS_ACTIVE TINYINT(1) DEFAULT 0,
    ORG_UUID VARCHAR(100) NOT NULL,
    PRIMARY KEY(ORG_ID),
    CONSTRAINT `FK_ORG_ID_PARENT` FOREIGN KEY (ORG_ID_PARENT) REFERENCES `ORGANIZATION` (ORG_ID),
    CONSTRAINT `FK_ORG_ID_GROUP_HEAD` FOREIGN KEY (ORG_ID_GROUP_HEAD) REFERENCES `ORGANIZATION` (ORG_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=COMPRESSED;

COMMIT;