USE pro_business_db;

-- pro_business_db.MODULE definition
CREATE TABLE IF NOT EXISTS MODULE (
    MOD_ID INT(11) NOT NULL AUTO_INCREMENT,
    MOD_LABEL VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (MOD_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=COMPRESSED;

-- pro_business_db.STATUS definition
CREATE TABLE IF NOT EXISTS STATUS (
    ID INT NOT NULL auto_increment,
    NAME VARCHAR(30) NOT NULL,
    MODULE_ID INT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT `FK_STATUS_MODULE_ID` FOREIGN KEY (MODULE_ID) REFERENCES MODULE(MOD_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- pro_business_db.FUNCTIONALITY definition
CREATE TABLE IF NOT EXISTS FUNCTIONALITY (
    FUN_ID INT(11) NOT NULL auto_increment,
    FUN_LABEL VARCHAR(100) NOT NULL UNIQUE,
    MOD_ID INT(11),
    PRIMARY KEY(FUN_ID),
    CONSTRAINT `FK_FUN_MOD_ID` FOREIGN KEY (MOD_ID) REFERENCES `MODULE` (MOD_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=COMPRESSED;

COMMIT;