USE pro_business_db;

-- pro_business_db.ROLE definition
CREATE TABLE IF NOT EXISTS ROLE (
    ROLE_ID INT(11) NOT NULL AUTO_INCREMENT,
    ROLE_LABEL VARCHAR(100) NOT NULL UNIQUE,
    CODE_TYPE_USER VARCHAR(1),
    MOD_ID INT(11),
    PRIMARY KEY (ROLE_ID),
    CONSTRAINT `FK_ROLE_MOD_ID` FOREIGN KEY (MOD_ID) REFERENCES `MODULE` (MOD_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=COMPRESSED;

-- pro_business_db.ROLE_FUN definition
CREATE TABLE IF NOT EXISTS ROLE_FUN (
    ROLE_ID INT(11) NOT NULL,
    FUN_ID INT(11) NOT NULL,
    PRIMARY KEY(ROLE_ID, FUN_ID),
    CONSTRAINT `FK_RF_FUN_ID` FOREIGN KEY (FUN_ID) REFERENCES `FUNCTIONALITY` (FUN_ID),
    CONSTRAINT `FK_RF_ROLE_ID` FOREIGN KEY (ROLE_ID) REFERENCES `ROLE` (ROLE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPRESSED;

COMMIT;