USE pro_business_db;

-- pro_business_db.PROFILE definition
CREATE TABLE IF NOT EXISTS PROFILE (
        PRO_ID INT(11) NOT NULL auto_increment,
        PRO_LABEL VARCHAR(100) NOT NULL UNIQUE,
        CODE_TYPE_USER VARCHAR(1),
        ORG_ID INT(11) NOT NULL,
        PRIMARY KEY(PRO_ID),
        CONSTRAINT `FK_PROFILE_ORGANIZATION` FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=COMPRESSED;

-- pro_business_db.PRO_ROLE definition
CREATE TABLE IF NOT EXISTS PRO_ROLE (
        ROLE_ID INT(11) NOT NULL,
        PRO_ID INT(11) NOT NULL,
        PRIMARY KEY(ROLE_ID, PRO_ID),
        CONSTRAINT `FK_PR_ROLE_ID` FOREIGN KEY (ROLE_ID) REFERENCES `ROLE` (ROLE_ID),
        CONSTRAINT `FK_PR_PRO_ID` FOREIGN KEY (PRO_ID) REFERENCES `PROFILE` (PRO_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPRESSED;

COMMIT;