USE pro_business_db;

-- pro_business_db.USER definition
CREATE TABLE IF NOT EXISTS USER (
    USER_ID INT(11) NOT NULL AUTO_INCREMENT,
    USER_ALIAS VARCHAR(50) UNIQUE,
    USER_EMAIL VARCHAR(100) UNIQUE,
    PRO_ID INT(11),
    ORG_ID INT(11),
    CODE_TYPE_USER VARCHAR(1),
    IS_ENABLED TINYINT(1) DEFAULT 0,
    IS_ACCOUNT_NOT_LOCKED TINYINT(1) DEFAULT 1,
    USER_PASSWORD TEXT NOT NULL,
    USER_UUID VARCHAR(100),
    PRIMARY KEY(USER_ID),
    CONSTRAINT `FK_USER_PRO_ID` FOREIGN KEY (PRO_ID) REFERENCES `PROFILE` (PRO_ID),
    CONSTRAINT `FK_USER_ORGANIZATION` FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=COMPRESSED;

COMMIT;