USE pro_business_db;

ALTER TABLE SUPPLIER
    ADD COLUMN ORG_ID INT(11) DEFAULT NULL
    AFTER CREATION_DATE;

ALTER TABLE SUPPLIER
    ADD CONSTRAINT FK_SUP_ORG_ID
    FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

ALTER TABLE PRODUCT
    ADD COLUMN ORG_ID INT(11) DEFAULT NULL
    AFTER CREATION_DATE;

ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_ORG_ID
    FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

ALTER TABLE PRODUCT_FAMILY
    ADD COLUMN ORG_ID INT(11) DEFAULT NULL
    AFTER NAME;

ALTER TABLE PRODUCT_FAMILY
    ADD CONSTRAINT FK_PRODUCT_FAMILY_ORG_ID
        FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

ALTER TABLE SUPPLIER_ORDER
    ADD COLUMN ORG_ID INT(11) DEFAULT NULL
    AFTER SUPPLIER_ORDER_NUMBER;

ALTER TABLE SUPPLIER_ORDER
    ADD CONSTRAINT FK_ORDER_ORG_ID
        FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

ALTER TABLE SUPPLIER_ORDER_ITEM
    ADD COLUMN ORG_ID INT(11) DEFAULT NULL
    AFTER DISCOUNT;

ALTER TABLE SUPPLIER_ORDER_ITEM
    ADD CONSTRAINT FK_ORDER_ITEM_ORG_ID
        FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

ALTER TABLE SUPPLIER_ORDER_PARAMS
    ADD CONSTRAINT FK_ORDER_PARAMS_ORG_ID
        FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

COMMIT;