USE pro_business_db;

ALTER TABLE
    SUPPLIER
    ADD
        COLUMN ORG_ID INT(11) DEFAULT NULL
    AFTER
        CREATION_DATE;

ALTER TABLE SUPPLIER
    ADD
        CONSTRAINT FK_SUP_ORG_ID
        FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

COMMIT;