USE pro_business_db;

-- pro_business_db.RECEPTION definition
CREATE TABLE IF NOT EXISTS RECEPTION (
    RECEPTION_ID BIGINT NOT NULL auto_increment,
    CREATION_DATE DATETIME NOT NULL,
    DESCRIPTION TEXT,
    ORG_ID INT,
    SUPPLIER_ID BIGINT,
    UUID VARCHAR(100) NOT NULL,
    PRIMARY KEY(RECEPTION_ID),
    CONSTRAINT `FK_RECEPTION_ORGANIZATION` FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID),
    CONSTRAINT `FK_RECEPTION_ORDER_SUPPLIER` FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID)
)ENGINE=InnoDB CHARACTER SET=UTF8MB3;

-- pro_business_db.ITEM_RECEPTION definition
CREATE TABLE IF NOT EXISTS ITEM_RECEPTION (
    RECEPTION_ID BIGINT NOT NULL,
    SUPPLIER_ORDER_ITEM_ID BIGINT NOT NULL,
    QUANTITY DECIMAL(11, 2),
    DATE DATETIME,
    PRIMARY KEY(RECEPTION_ID, SUPPLIER_ORDER_ITEM_ID),
    CONSTRAINT `FK_ITEM_RECEPTION_RECEPTION_ID` FOREIGN KEY (RECEPTION_ID) REFERENCES `RECEPTION` (RECEPTION_ID),
    CONSTRAINT `FK_ITEM_RECEPTION_SUPPLIER_ORDER_ITEM_ID` FOREIGN KEY (SUPPLIER_ORDER_ITEM_ID) REFERENCES `SUPPLIER_ORDER_ITEM` (ID_SUPPLIER_ORDER_ITEM)
)ENGINE=InnoDB CHARACTER SET=UTF8MB3;

ALTER TABLE ITEM_RECEPTION
    ADD UUID varchar(100) NOT NULL
    AFTER SUPPLIER_ORDER_ITEM_ID;

ALTER TABLE ITEM_RECEPTION
    ADD COLUMN ORG_ID INT(11) DEFAULT NULL
    AFTER QUANTITY;

-- change constraint name to FK_ORG_ID
ALTER TABLE ITEM_RECEPTION
    ADD CONSTRAINT FK_ITEM_RECEP_ID
    FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ORG_ID);

ALTER TABLE SUPPLIER_ORDER_ITEM
    ADD COLUMN REMAINING_QUANTITY DECIMAL(11, 2) DEFAULT NULL
    AFTER QUANTITY;

ALTER TABLE ITEM_RECEPTION
    ADD COLUMN ID_SUPPLIER_ORDER BIGINT DEFAULT NULL
    AFTER SUPPLIER_ORDER_ITEM_ID;

ALTER TABLE ITEM_RECEPTION
    ADD CONSTRAINT FK_ID_SUPPLIER_ORDER
        FOREIGN KEY (ID_SUPPLIER_ORDER) REFERENCES SUPPLIER_ORDER(ID_SUPPLIER_ORDER);


COMMIT;
