spring:
  datasource:
    url : jdbc:mysql://localhost:3306/pro_business_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username : 'probusiness'
    password : '0000'
  jpa:
    hibernate.ddl-auto : none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect