spring:
  datasource:
    url : jdbc:mysql://localhost:3306/business
    username : root
    password : root
  jpa:
    hibernate.ddl-auto : create
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect