spring:
  datasource:
    url : jdbc:mysql://localhost:3306/pro_business_db
    username : probusiness
    password : 0000
  jpa:
    hibernate.ddl-auto : create
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect