USE pro_business_db;

-- pro_business_db.PRODUCT_FAMILY definition
CREATE TABLE IF NOT EXISTS PRODUCT_FAMILY (
    ID_PRODUCT_FAMILY BIGINT NOT NULL auto_increment,
    UUID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID_PRODUCT_FAMILY)
    )ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- pro_business_db.PRODUCT definition
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID_PRODUCT BIGINT NOT NULL auto_increment,
    UUID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    MEASURE_UNITE VARCHAR(30),
    VAT_RATE DECIMAL(11, 3),
    BUYING_PRICE DECIMAL(11, 3),
    RESELLER_PRICE DECIMAL(11, 3),
    PUBLIC_SALE_PRICE DECIMAL(11, 3),
    CURRENT_STOCK BIGINT,
    INITIAL_STOCK BIGINT,
    INITIAL_STOCK_DATE DATE,
    MINIMAL_STOCK BIGINT,
    MAXIMAL_STOCK BIGINT,
    CREATION_DATE DATE,
    ID_PRODUCT_FAMILY BIGINT,
    PRIMARY KEY(ID_PRODUCT),
    CONSTRAINT `FK_PRODCUT_FAMILY` FOREIGN KEY (ID_PRODUCT_FAMILY) REFERENCES `PRODUCT_FAMILY` (ID_PRODUCT_FAMILY)
    )ENGINE=InnoDB CHARACTER SET=UTF8;

INSERT INTO PRODUCT_FAMILY (name, uuid) values ("Test", 1);

COMMIT;

