USE pro_business_db;

-- pro_business_db.PRODUCT definition

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID_PRODUCT BIGINT NOT NULL auto_increment,
    UUID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    MEASURE_UNITE VARCHAR(30),
    VAT_RATE DECIMAL(11, 3),
    BUYING_PRICE DECIMAL(11, 3),
    RESELLER_PRICE DECIMAL(11, 3),
    PUBLIC_SALE_PRICE DECIMAL(11, 3),
    CURRENT_STOCK BIGINT,
    INITIAL_STOCK BIGINT,
    INITIAL_STOCK_DATE DATE,
    MINIMAL_STOCK BIGINT,
    MAXIMAL_STOCK BIGINT,
    CREATION_DATE DATE,
    PRIMARY KEY(ID_PRODUCT),
    KEY `FK_PRODCUT_FAMILY` (`ID_PRODUCT_FAMILY`),
    CONSTRAINT `FK_PRODCUT_FAMILY` FOREIGN KEY (`ID_PRODUCT_FAMILY`) REFERENCES `PRODUCT_FAMILY` (`ID_PRODUCT_FAMILY`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB CHARACTER SET=UTF8MB4;

COMMIT;